name: Backup to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install pigz
      run: sudo apt-get install pigz

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Create a tarball and compress with pigz
      run: |
        tar -cf - . | pigz -9 > repo.tar.gz

    - name: Upload to Google Drive
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "${GOOGLE_CREDENTIALS}" > credentials.json
        python upload_to_drive.py repo.tar.gz
