name: Backup to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pigz rclone

    - name: Create a tarball and compress with pigz
      run: |
        tar -cf - . | pigz -9 > repo.tar.gz

    - name: Configure rclone
      run: |
        echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

    - name: Upload to Google Drive with rclone
      run: |
        rclone copy repo.tar.gz remote:backup-folder/
